<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: event.proto

namespace App\Event\Metadata;

class Event
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\x9C\x01\x0A\x0Bevent.proto\x12\x08protobuf\"O\x0A\x0BUserCreated\x12\x10\x0A\x08userName\x18\x01 \x01(\x09\x12\x0D\x0A\x05email\x18\x02 \x01(\x09\x12\x0E\x0A\x06userID\x18\x03 \x01(\x09\x12\x0F\x0A\x07version\x18\x04 \x01(\x03B*\xCA\x02\x12App\\Event\\ProtoBuf\xE2\x02\x12App\\Event\\Metadatab\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

